=== Garso777/Ejercicios-HTML-CSS1/Textos/DTD/Ejercicio6/Menu6.2.dtd
<!ELEMENT menus (menu+)>
<!ELEMENT menu (comida, bebida)>
<!ATTLIST menu
          precio CDATA #REQUIRED
          tarjeta CDATA #IMPLIED>
<!ELEMENT comida (primero, segundo, postre)>
<!ELEMENT primero (opcion+)>
<!ELEMENT opcion (#PCDATA)>
<!ATTLIST opcion
          tipo CDATA #REQUIRED>
<!ELEMENT segundo (opcion)>
<!ELEMENT postre (opcion)>
<!ELEMENT bebida (opcion)>
<!ATTLIST bebida
          tamanyo CDATA #REQUIRED>

=== Garso777/Ejercicios-HTML-CSS1/Textos/DTD/Ejercicio6/Menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menus SYSTEM "file:/C:/Users/usu07d/Documents/Marcas/DTD/Ejercicio6/Menu6.2.dtd">
<menus>
<menu precio="10" tarjeta="no">
 <comida>
 <primero>
 sopa
 <opcion tipo="sobre" />
 </primero>
 <segundo>
 chuleta
 <opcion tipo="cerdo" />
 </segundo>
 <postre>
 flan
 <opcion tipo="huevo" />
 </postre>
 </comida>
 <bebida tamanyo="0.5">
 agua
 </bebida>
</menu>
<menu precio="25">
 <comida>
 <primero>
 entremeses
 <opcion tipo="ibericos" />
 </primero>
 <segundo>
 chuleton
 <opcion tipo="buey" />
 </segundo>
 <postre>
 arroz con leche
 <opcion tipo="casero" />
 </postre>
 </comida>
 <bebida tamanyo="1">
 rioja
<opcion tipo="rioja" />
 </bebida>
</menu>
</menus>
